protected/controllers/AdminController.php
<?php

namespace app\controllers;

use app\models\Admin;
use app\models\User;
use app\models\Video;
use app\models\VideoCategory;
use Yii;
use yii\base\Exception;
use yii\filters\AccessControl;
use app\models\AdminLoginForm;
use app\models\Uploader;
use yii\helpers\Url;
use yii\web\HttpException;
use yii\web\UploadedFile;

class AdminController extends BaseController {

	public $layout = 'admin';

	public function behaviors() {
		return [
			'access' => [
				'class' => AccessControl::className(),
				'rules' => [
					[
						'actions' => ['login', 'logout', 'error'],
						'allow'   => true,
					],
					[
						'allow' => true,
						'roles' => [Admin::ROLE],
					],
				],
				'denyCallback' => function($rule, $action) {
					/** @var User $user */
					$user = Yii::$app->user->getIdentity();
					if ($user && $user->role != Admin::ROLE) {
						throw new HttpException(403, Yii::t('common', 'You are not allowed to perform this action'));
					}
					/** @var \yii\base\InlineAction $action */
					return $this->redirect(Url::to(['login']));
				},
			],
		];
	}

	public function actionLogin() {
		if (!\Yii::$app->user->isGuest) {
			return $this->redirect(['index']);
		}

		$model = new AdminLoginForm();
		if ($model->load(Yii::$app->request->post()) && $model->login()) {
			return $this->redirect(['index']);
		} else {
			return $this->render('/main/login', [
				'model' => $model,
			]);
		}
	}

	public function actionIndex() {
		return $this->redirect(['uploader-list']);
	}

	public function actionViewerList() {
		$users = User::find()->all();
		return $this->render('viewer-list', [
			'users' => $users,
		]);
	}

	public function actionViewerAdd() {
		$user = new User();

		if (Yii::$app->request->isPost) {
			$user->load(Yii::$app->request->post());
			$success = $user->save();
			Yii::$app->session->setFlash(Yii::$app->controller->action->id, $success?: current($user->getFirstErrors()));
			if ($success) {
				$this->redirect(['viewer-list']);
			}
		}

		return $this->render('viewer-edit', [
			'user' => $user
		]);
	}

	public function actionViewerEdit($id) {
		$user = User::findOne($id);

		if (Yii::$app->request->isPost) {
			$user->load(Yii::$app->request->post());
			$success = $user->save();
			Yii::$app->session->setFlash(Yii::$app->controller->action->id, $success?: current($user->getFirstErrors()));
			if ($success) {
				$this->redirect(['viewer-list']);
			}
		}

		return $this->render('viewer-edit', [
			'user' => $user
		]);
	}

	public function actionUploaderList() {
		$users = Uploader::find()->all();
		return $this->render('uploader-list', [
			'users' => $users,
		]);
	}

	public function actionUploaderAdd() {
		$uploader = new Uploader();
		if (Yii::$app->request->isPost) {
			$uploader->load(Yii::$app->request->post());
			$success = $uploader->save();
			Yii::$app->session->setFlash('uploader', $success);
			if ($success) {
				return $this->redirect(['admin/uploader-list']);
			}
		}
		return $this->render('uploader-edit', [
			'user' => $uploader,
		]);
	}

	public function actionUploaderEdit($id) {
		$uploader = Uploader::findOne($id);
		if (Yii::$app->request->isPost) {
			$uploader->load(Yii::$app->request->post());
			$success = $uploader->save();
			Yii::$app->session->setFlash('uploader', $success);
			if ($success) {
				return $this->redirect(['admin/uploader-list']);
			}
		}
		return $this->render('uploader-edit', [
			'user' => $uploader,
		]);
	}

	public function actionUploaderDetail($id) {
		$uploader = Uploader::find()->with('videos', 'videos.parts')->where('id = :id', [':id' => $id])->one();

		return $this->render('uploader-detail', [
			'user' => $uploader,
		]);
	}

	public function actionVideoAdd($uploaderId) {
		$video = new Video();

		if (Yii::$app->request->isPost) {
			$video->load(Yii::$app->request->post());
			$video->uploaderId = $uploaderId;
			$success           = $video->save();

			if ($success) {
				$success = $video->saveParts();
				$video->saveDocuments();
				Yii::$app->session->setFlash('video', $success);
				if ($success) {
					return $this->redirect(['admin/uploader-detail', 'id' => $uploaderId]);
				}
			}
		}

		return $this->render('video-edit', [
			'model' => $video,
		]);
	}

	public function actionVideoEdit($id) {
		/** @var Video $video */
		$video = Video::find()->where('id = :id', [':id' => $id])->one();

		if (Yii::$app->request->isPost) {
			$video->load(Yii::$app->request->post());
			$success = $video->save();

			if ($success) {
				$success = $video->saveParts();
				$video->saveDocuments();
				Yii::$app->session->setFlash('video', $success);
				if ($success) {
					return $this->redirect('');
				}
			}
		}

		return $this->render('video-edit', [
			'model' => $video,
		]);
	}

	public function actionVideoCategoryList() {
		$categories = VideoCategory::find()->all();
		return $this->render('video-category-list', [
			'categories' => $categories,
		]);
	}

	public function actionVideoCategoryAdd() {
		$category = new VideoCategory();

		if (Yii::$app->request->isPost) {
			$category->load(Yii::$app->request->post());
			$success = $category->save();

			if ($success) {
				Yii::$app->session->setFlash('video-category', $success);
				if ($success) {
					return $this->redirect(['admin/video-category-list']);
				}
			}
		}

		return $this->render('video-category-edit', [
			'model' => $category,
		]);
	}

	public function actionVideoCategoryEdit($id) {
		$category = VideoCategory::findOne($id);

		if (Yii::$app->request->isPost) {
			$category->load(Yii::$app->request->post());
			$success = $category->save();

			if ($success) {
				Yii::$app->session->setFlash('video-category', $success);
				if ($success) {
					return $this->redirect(['admin/video-category-list']);
				}
			}
		}

		return $this->render('video-category-edit', [
			'model' => $category,
		]);
	}

	public function actionModelDelete($id, $model = 'user', $redirect = ['admin/viewer-list']) {
		$model   = ucfirst($model);
		$class   = '\app\models\\' . $model;
		$success = $class::findOne($id)->delete();
		Yii::$app->session->setFlash(strtolower($model), $success);
		return $this->redirect($redirect);
	}
}

protected/views/admin/uploader-detail.php
<?php
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use \yii\helpers\Url;

/**
 * @var $this  yii\web\View
 * @var $user  \app\models\Uploader
 */
$this->title = Yii::t('common', 'Uploader detail');
?>

<div class="text-right">
	<a href="<?= Url::to(['admin/uploader-edit', 'id' => $user->id]) ?>" class="btn btn-success"><?= Yii::t('common', 'Edit') ?></a>
</div>

<div class="form-group">
	<b><?= $user->getAttributeLabel('title') ?></b> : <?= $user->title ?>
</div>
<div class="form-group">
	<b><?= $user->getAttributeLabel('contactName') ?></b> : <?= $user->contactName ?>
</div>
<div class="form-group">
	<b><?= $user->getAttributeLabel('mail') ?></b> : <a href="mailto:<?= $user->mail ?>"><?= $user->mail ?></a>
</div>
<div class="form-group">
	<b><?= $user->getAttributeLabel('phone') ?></b> : <?= $user->phone ?>
</div>
<div class="form-group">
	<b><?= $user->getAttributeLabel('address') ?></b> : <?= $user->address ?>
</div>
<div class="form-group">
	<b><?= Yii::t('common', 'Upload') ?></b> : <?= $user->getVideosCount() ?>
</div>

<?php if (count($user->videos)) { ?>
<table class="table table-hover">
	<tr>
		<th></th>
		<th><?= $user->videos[0]->getAttributeLabel('title') ?></th>
		<th><?= $user->videos[0]->getAttributeLabel('rating') ?></th>
		<th><?= Yii::t('common', 'count') ?></th>
		<th><?= Yii::t('common', 'time') ?></th>
		<th></th>
	</tr>
	<?php foreach ($user->videos as $video) { ?>
		<tr>
			<td><?= $video->id ?></td>
			<td><?= $video->title ?></td>
			<td><?= $video->rating ?></td>
			<td><?= $video->getPartsCount() ?></td>
			<td><?= $video->getTotalDuration() ?></td>
			<td>
				<a href="<?= Url::to(['admin/video-edit', 'id' => $video->id]) ?>" class="btn btn-info"><span class="glyphicon glyphicon-pencil"></span></a>
				<a href="<?= Url::to(['admin/model-delete', 'id' => $video->id, 'model' => 'video', 'redirect' => Url::to(['admin/uploader-detail', 'id' => $user->id])]) ?>" class="btn btn-danger js-confirm" data-confirm-text="<?= Yii::t('common', 'Are you sure?') ?>"><span class="glyphicon glyphicon-remove"></span></a>
			</td>
		</tr>
	<?php } ?>
</table>
<?php } ?>

<div class="text-left">
	<a href="<?= Url::to(['admin/video-add', 'uploaderId' => $user->id]) ?>" class="btn btn-primary"><?= Yii::t('common', 'Upload') ?></a>
</div>

protected/views/admin/uploader-edit.php
<?php
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

/**
 * @var $this  yii\web\View
 * @var $user  \app\models\Uploader
 */
$this->title = Yii::t('common', 'Uploader edit');
?>

<?php $form = ActiveForm::begin([
	'id'          => 'user-edit-form',
	'options'     => ['class' => 'form-vertical'],
	'fieldConfig' => [
		'template' => "<div class=\"row\"><div class=\"col-sm-4\">{label}</div>\n<div class=\"col-sm-8\">{input}{error}</div></div>",
	],
]); ?>

<?= $form->field($user, 'title') ?>
<?= $form->field($user, 'contactName') ?>
<?= $form->field($user, 'mail') ?>
<?= $form->field($user, 'phone') ?>
<?= $form->field($user, 'address') ?>

<div class="form-group">
	<?= Html::submitButton(Yii::t('common', 'Save'), ['class' => 'btn btn-primary']) ?>
	<?= Html::a(Yii::t('common', 'Back to list'), ['admin/uploader-list'], ['class' => 'btn btn-link']) ?>
</div>

<?php ActiveForm::end(); ?>

protected/views/admin/uploader-list.php
<?php
use yii\helpers\Html;
use yii\helpers\Url;
use \app\models\Uploader;

/**
 * @var $this  yii\web\View
 * @var $users \app\models\Uploader[]
 */
$this->title = Yii::t('common', 'Uploader list'); ?>

<?= $this->render('@parts/simple-flash', ['flashId' => 'uploader']) ?>

<div class="form-group">
	<a href="<?= Url::to(['admin/uploader-add']) ?>" class="btn btn-success btn-lg"><?= Yii::t('common', 'Add') ?></a>
</div>

<?php if (count($users) == 0) {
	echo '<div class="alert alert-warning">' . Yii::t('common', 'Empty list') . '</div>';
	return;
} ?>

<table class="table table-hover">
	<tr>
		<th></th>
		<th><?= $users[0]->getAttributeLabel('title') ?></th>
		<th><?= $users[0]->getAttributeLabel('contactName') ?></th>
		<th><?= Yii::t('common', 'Video count') ?></th>
		<th></th>
	</tr>
	<?php foreach ($users as $user) { ?>
		<tr>
			<td><?= $user->id ?></td>
			<td>
				<a href="<?= Url::to(['admin/uploader-detail', 'id' => $user->id]) ?>"><?= $user->title ?></a>
			</td>
			<td><?= $user->contactName ?></td>
			<td><?= $user->getVideosCount() ?></td>
			<td class="text-right">
				<a href="<?= Url::to(['admin/uploader-edit', 'id' => $user->id]) ?>" class="btn btn-info"><span class="glyphicon glyphicon-pencil"></span></a>
				<a href="<?= Url::to(['admin/model-delete', 'id' => $user->id, 'model' => 'uploader', 'redirect' => Url::to(['admin/uploader-list'])]) ?>" class="btn btn-danger js-confirm" data-confirm-text="<?= Yii::t('common', 'Are you sure?') ?>"><span class="glyphicon glyphicon-remove"></span></a>
			</td>
		</tr>
	<?php } ?>
</table>

protected/views/admin/video-category-edit.php
<?php
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use \yii\helpers\ArrayHelper;
use \yii\helpers\Url;
use \yii\helpers\StringHelper;

/**
 * @var $this   yii\web\View
 * @var $model  \app\models\VideoCategory
 */
$this->title = Yii::t('common', 'Video category edit');
?>

<?php $form = ActiveForm::begin([
	'options'     => ['class' => 'form-vertical'],
	'fieldConfig' => [
		'template' => "<div class=\"row\"><div class=\"col-sm-4\">{label}</div>\n<div class=\"col-sm-8\">{input}{error}</div></div>",
	],
]); ?>

<div class="row">
	<div class="col-sm-6">
		<?= $form->field($model, 'title') ?>
	</div>
</div>

<div class="form-group">
	<?= Html::submitButton(Yii::t('common', 'Save'), ['class' => 'btn btn-primary']) ?>
	<?= Html::a(Yii::t('common', 'Back to list'), ['admin/video-category-list'], ['class' => 'btn btn-link']) ?>
</div>

<?php ActiveForm::end(); ?>

protected/views/admin/video-category-list.php
<?php
use yii\helpers\Html;
use yii\helpers\Url;

/**
 * @var $this       yii\web\View
 * @var $categories \app\models\VideoCategory[]
 */
$this->title = Yii::t('common', 'Category list'); ?>

<?= $this->render('@parts/simple-flash', ['flashId' => 'video-category']) ?>

<div class="form-group">
	<a href="<?= Url::to(['admin/video-category-add']) ?>" class="btn btn-success btn-lg"><?= Yii::t('common', 'Add') ?></a>
</div>

<?php if (count($categories) == 0) {
	echo '<div class="alert alert-warning">' . Yii::t('common', 'Empty list') . '</div>';
	return;
} ?>

<table class="table">
	<tr>
		<th></th>
		<th><?= $categories[0]->getAttributeLabel('title') ?></th>
		<th><?= $categories[0]->getAttributeLabel('created') ?></th>
		<th></th>
	</tr>
	<?php foreach ($categories as $category) { ?>
		<tr>
			<td><?= $category->id ?></td>
			<td><?= $category->title ?></td>
			<td><?= $category->created ?></td>
			<td>
				<a href="<?= Url::to(['admin/video-category-edit', 'id' => $category->id]) ?>" class="btn btn-info"><span class="glyphicon glyphicon-pencil"></span></a>
				<a href="<?= Url::to(['admin/model-delete', 'model' => \yii\helpers\StringHelper::basename($category::className()), 'id' => $category->id, 'redirect' => Url::to(['video-category-list'])]) ?>"
				   class="btn btn-danger js-confirm" data-confirm-text="<?= Yii::t('common', 'Are you sure?') ?>"><span class="glyphicon glyphicon-remove"></span></a>
			</td>
		</tr>
	<?php } ?>
</table>

protected/views/admin/video-edit.php
<?php
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use \yii\helpers\ArrayHelper;
use \yii\helpers\Url;
use \yii\helpers\StringHelper;

/**
 * @var $this   yii\web\View
 * @var $model  \app\models\Video
 */
$this->title = Yii::t('common', 'Video edit');
?>

<?php $form = ActiveForm::begin([
	'options'     => ['enctype' => 'multipart/form-data', 'class' => 'form-vertical'],
	'fieldConfig' => [
		'template' => "<div class=\"row\"><div class=\"col-sm-5\">{label}</div>\n<div class=\"col-sm-7\">{input}{error}</div></div>",
	],
]); ?>

<div class="form-group">
	<?php if (count($model->parts)) { ?>
		<table class="table table-condensed">
			<tr>
				<th><?= $model->parts[0]->getAttributeLabel('title') ?></th>
				<th><?= $model->parts[0]->getAttributeLabel('duration') ?></th>
				<th><?= $model->parts[0]->getAttributeLabel('preview') ?></th>
				<th></th>
			</tr>
			<?php foreach ($model->parts as $videoPart) { ?>
				<tr>
					<td><?= $videoPart->title ?></td>
					<td><?= $videoPart->duration ?></td>
					<td><?= Html::img($videoPart->preview, ['alt' => $videoPart->preview]) ?></td>
					<td class="text-right"><?= Html::a('<span class="glyphicon glyphicon-remove"></span>', ['admin/model-delete', 'id' => $videoPart->id, 'model' => StringHelper::basename($videoPart::className()), 'redirect' => Url::to(['video-edit', 'id' => $model->id])], ['class' => 'btn btn-sm btn-danger js-confirm', 'data-confirm-text' => Yii::t('common', 'Are you sure?') ]) ?></td>
				</tr>
			<?php } ?>
		</table>
	<?php } ?>
	<div class="row js-row-for-clone">
		<div class="col-sm-4">
			<?= $form->field($model, 'partTitles[]') ?>
		</div>
		<div class="col-sm-4">
			<?= $form->field($model, 'sources[]', ['template' => '{input}{error}'])
				->fileInput(['multiple' => true]) ?>
		</div>
		<div class="col-sm-4">
			<?= $form->field($model, 'durations[]') ?>
		</div>
		<div class="col-sm-4">
			<?= $form->field($model, 'previews[]')
				->fileInput(['multiple' => true]) ?>
		</div>
	</div>
	<div class="form-group">
		<button class="btn btn-primary js-clone-row" data-target=".js-row-for-clone">
			<span class="glyphicon glyphicon-plus"></span>
		</button>
		<button class="btn btn-danger js-delete-row" data-target=".js-row-for-clone">
			<span class="glyphicon glyphicon-minus"></span>
		</button>
	</div>
</div>

<div class="row">
	<div class="col-sm-8">
		<div class="form-group">
			<?= $form->field($model, 'title') ?>
			<?= $form->field($model, 'description')->textarea(['rows' => 8]) ?>
			<?= $form->field($model, 'payment') ?>
			<?= $form->field($model, 'categoryId')->dropDownList(ArrayHelper::map(\app\models\VideoCategory::find()->all(), 'id', 'title')) ?>
		</div>

		<table class="table table-condensed">
			<?php foreach ($model->documents as $document) { ?>
				<tr>
					<td><?= $document->getName() ?></td>
					<td class="text-right"><?= Html::a('<span class="glyphicon glyphicon-remove"></span>', ['admin/model-delete', 'id' => $document->id, 'model' => StringHelper::basename($document::className()), 'redirect' => Url::to(['video-edit', 'id' => $model->id])], ['class' => 'btn btn-sm btn-danger js-confirm', 'data-confirm-text' => Yii::t('common', 'Are you sure?') ]) ?></td>
				</tr>
			<?php } ?>
		</table>
		<?php
		for ($i = 0; $i < $model::MAX_DOCUMENTS - count($model->documents); $i++) {
			echo $form->field($model, 'documentFiles[]')->fileInput(['multiple' => true]);
		}
		?>
	</div>
</div>

<div class="form-group">
	<?= Html::submitButton(Yii::t('common', 'Save'), ['class' => 'btn btn-primary']) ?>
	<?= Html::a(Yii::t('common', 'Back to list'), ['admin/uploader-list'], ['class' => 'btn btn-link']) ?>
</div>

<?php ActiveForm::end(); ?>

protected/views/admin/viewer-edit.php
<?php
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

/**
 * @var $this  yii\web\View
 * @var $user  \app\models\User
 */
$this->title = Yii::t('common', 'Viewer edit'); ?>

<?= $this->render('@parts/simple-flash', ['flashId' => Yii::$app->controller->action->id]) ?>

<?php $form = ActiveForm::begin([
	'id'          => 'user-edit-form',
	'options'     => ['class' => 'form-vertical'],
	'fieldConfig' => [
		'template' => "<div class=\"row\"><div class=\"col-sm-4\">{label}</div>\n<div class=\"col-sm-8\">{input}{error}</div></div>",
	],
]); ?>

<?= $form->field($user, 'firstName') ?>
<?= $form->field($user, 'firstNameWrite') ?>
<?= $form->field($user, 'password')->passwordInput(['value' => '']) ?>
<?= $form->field($user, 'email') ?>
<?= $form->field($user, 'zip') ?>
<?= $form->field($user, 'prefecture') ?>
<?= $form->field($user, 'city') ?>
<?= $form->field($user, 'address') ?>
<?= $form->field($user, 'occupation') ?>
<?= $form->field($user, 'birthday', ['inputOptions' => ['class' => 'form-control js-datepicker']]) ?>

<div class="form-group">
	<?= Html::submitButton(Yii::t('common', 'Save'), ['class' => 'btn btn-primary']) ?>
	<?= Html::a(Yii::t('common', 'Back to list'), ['admin/viewer-list'], ['class' => 'btn btn-link']) ?>
</div>

<?php ActiveForm::end(); ?>

protected/views/admin/viewer-list.php
<?php
use yii\helpers\Html;
use yii\helpers\Url;

/**
 * @var $this  yii\web\View
 * @var $users \app\models\User[]
 */
$this->title = Yii::t('common', 'Viewer list'); ?>

<?= $this->render('@parts/simple-flash', ['flashId' => 'delete-user']) ?>

<div class="form-group">
	<a href="<?= Url::to(['admin/viewer-add']) ?>" class="btn btn-success btn-lg"><?= Yii::t('common', 'Add') ?></a>
</div>

<?php if (count($users) == 0) {
	echo '<div class="alert alert-warning">' . Yii::t('common', 'Empty list') . '</div>';
	return;
} ?>

<table class="table">
	<tr>
		<th></th>
		<th><?= $users[0]->getAttributeLabel('firstName') ?></th>
		<th><?= $users[0]->getAttributeLabel('firstNameWrite') ?></th>
		<th><?= $users[0]->getAttributeLabel('email') ?></th>
		<th><?= $users[0]->getAttributeLabel('address') ?></th>
		<th><?= Yii::t('common', 'Date of birth') ?></th>
		<th><?= $users[0]->getAttributeLabel('occupation') ?></th>
		<th></th>
	</tr>
	<?php foreach ($users as $user) { ?>
		<tr>
			<td><?= $user->id ?></td>
			<td><?= $user->firstName ?></td>
			<td><?= $user->firstNameWrite ?></td>
			<td><?= $user->email ?></td>
			<td><?= implode(', ', array_filter([$user->city, $user->address, $user->zip])) ?></td>
			<td><?= $user->birthday ?></td>
			<td><?= $user->occupation ?></td>
			<td>
				<a href="<?= Url::to(['admin/viewer-edit', 'id' => $user->id]) ?>" class="btn btn-info"><span class="glyphicon glyphicon-pencil"></span></a>
				<a href="<?= Url::to(['admin/model-delete', 'id' => $user->id]) ?>" class="btn btn-danger js-confirm" data-confirm-text="<?= Yii::t('common', 'Are you sure?') ?>"><span class="glyphicon glyphicon-remove"></span></a>
			</td>
		</tr>
	<?php } ?>
</table>