protected/controllers/AdminController.php
<?php

namespace app\controllers;

use app\models\Admin;
use app\models\User;
use app\models\Video;
use app\models\VideoCategory;
use Yii;
use yii\base\Exception;
use yii\filters\AccessControl;
use app\models\AdminLoginForm;
use app\models\Uploader;
use yii\helpers\Url;
use yii\web\HttpException;
use yii\web\UploadedFile;

class AdminController extends BaseController {

	public $layout = 'admin';

	public function behaviors() {
		return [
			'access' => [
				'class' => AccessControl::className(),
				'rules' => [
					[
						'actions' => ['login', 'logout', 'error'],
						'allow'   => true,
					],
					[
						'allow' => true,
						'roles' => [Admin::ROLE],
					],
				],
				'denyCallback' => function($rule, $action) {
					/** @var User $user */
					$user = Yii::$app->user->getIdentity();
					if ($user && $user->role != Admin::ROLE) {
						throw new HttpException(403, Yii::t('common', 'You are not allowed to perform this action'));
					}
					/** @var \yii\base\InlineAction $action */
					return $this->redirect(Url::to(['login']));
				},
			],
		];
	}

	public function actionLogin() {
		if (!\Yii::$app->user->isGuest) {
			return $this->redirect(['index']);
		}

		$model = new AdminLoginForm();
		if ($model->load(Yii::$app->request->post()) && $model->login()) {
			return $this->redirect(['index']);
		} else {
			return $this->render('/main/login', [
				'model' => $model,
			]);
		}
	}

	public function actionIndex() {
		return $this->redirect(['uploader-list']);
	}

	public function actionViewerList() {
		$users = User::find()->all();
		return $this->render('viewer-list', [
			'users' => $users,
		]);
	}

	public function actionViewerAdd() {
		$user = new User();

		if (Yii::$app->request->isPost) {
			$user->load(Yii::$app->request->post());
			$success = $user->save();
			Yii::$app->session->setFlash(Yii::$app->controller->action->id, $success?: current($user->getFirstErrors()));
			if ($success) {
				$this->redirect(['viewer-list']);
			}
		}

		return $this->render('viewer-edit', [
			'user' => $user
		]);
	}

	public function actionViewerEdit($id) {
		$user = User::findOne($id);

		if (Yii::$app->request->isPost) {
			$user->load(Yii::$app->request->post());
			$success = $user->save();
			Yii::$app->session->setFlash(Yii::$app->controller->action->id, $success?: current($user->getFirstErrors()));
			if ($success) {
				$this->redirect(['viewer-list']);
			}
		}

		return $this->render('viewer-edit', [
			'user' => $user
		]);
	}

	public function actionUploaderList() {
		$users = Uploader::find()->all();
		return $this->render('uploader-list', [
			'users' => $users,
		]);
	}

	public function actionUploaderAdd() {
		$uploader = new Uploader();
		if (Yii::$app->request->isPost) {
			$uploader->load(Yii::$app->request->post());
			$success = $uploader->save();
			Yii::$app->session->setFlash('uploader', $success);
			if ($success) {
				return $this->redirect(['admin/uploader-list']);
			}
		}
		return $this->render('uploader-edit', [
			'user' => $uploader,
		]);
	}

	public function actionUploaderEdit($id) {
		$uploader = Uploader::findOne($id);
		if (Yii::$app->request->isPost) {
			$uploader->load(Yii::$app->request->post());
			$success = $uploader->save();
			Yii::$app->session->setFlash('uploader', $success);
			if ($success) {
				return $this->redirect(['admin/uploader-list']);
			}
		}
		return $this->render('uploader-edit', [
			'user' => $uploader,
		]);
	}

	public function actionUploaderDetail($id) {
		$uploader = Uploader::find()->with('videos', 'videos.parts')->where('id = :id', [':id' => $id])->one();

		return $this->render('uploader-detail', [
			'user' => $uploader,
		]);
	}

	public function actionVideoAdd($uploaderId) {
		$video = new Video();

		if (Yii::$app->request->isPost) {
			$video->load(Yii::$app->request->post());
			$video->uploaderId = $uploaderId;
			$success           = $video->save();

			if ($success) {
				$success = $video->saveParts();
				$video->saveDocuments();
				Yii::$app->session->setFlash('video', $success);
				if ($success) {
					return $this->redirect(['admin/uploader-detail', 'id' => $uploaderId]);
				}
			}
		}

		return $this->render('video-edit', [
			'model' => $video,
		]);
	}

	public function actionVideoEdit($id) {
		/** @var Video $video */
		$video = Video::find()->where('id = :id', [':id' => $id])->one();

		if (Yii::$app->request->isPost) {
			$video->load(Yii::$app->request->post());
			$success = $video->save();

			if ($success) {
				$success = $video->saveParts();
				$video->saveDocuments();
				Yii::$app->session->setFlash('video', $success);
				if ($success) {
					return $this->redirect('');
				}
			}
		}

		return $this->render('video-edit', [
			'model' => $video,
		]);
	}

	public function actionVideoCategoryList() {
		$categories = VideoCategory::find()->all();
		return $this->render('video-category-list', [
			'categories' => $categories,
		]);
	}

	public function actionVideoCategoryAdd() {
		$category = new VideoCategory();

		if (Yii::$app->request->isPost) {
			$category->load(Yii::$app->request->post());
			$success = $category->save();

			if ($success) {
				Yii::$app->session->setFlash('video-category', $success);
				if ($success) {
					return $this->redirect(['admin/video-category-list']);
				}
			}
		}

		return $this->render('video-category-edit', [
			'model' => $category,
		]);
	}

	public function actionVideoCategoryEdit($id) {
		$category = VideoCategory::findOne($id);

		if (Yii::$app->request->isPost) {
			$category->load(Yii::$app->request->post());
			$success = $category->save();

			if ($success) {
				Yii::$app->session->setFlash('video-category', $success);
				if ($success) {
					return $this->redirect(['admin/video-category-list']);
				}
			}
		}

		return $this->render('video-category-edit', [
			'model' => $category,
		]);
	}

	public function actionModelDelete($id, $model = 'user', $redirect = ['admin/viewer-list']) {
		$model   = ucfirst($model);
		$class   = '\app\models\\' . $model;
		$success = $class::findOne($id)->delete();
		Yii::$app->session->setFlash(strtolower($model), $success);
		return $this->redirect($redirect);
	}
}

protected/controllers/MainController.php
<?php

namespace app\controllers;

use app\models\User;
use app\models\Admin;
use app\models\RegistrationForm;
use app\models\Video;
use app\models\VideoCategory;
use Yii;
use yii\filters\AccessControl;
use app\models\LoginForm;
use yii\web\HttpException;
use app\models\VideoDocument;

class MainController extends BaseController {

	public function behaviors() {
		return [
			'access' => [
				'class' => AccessControl::className(),
				'rules' => [
					[
						'actions' => ['login', 'logout', 'index', 'search-by-categories', 'registration', 'error'],
						'allow'   => true,
					],
					[
						'actions' => ['edit-profile'],
						'roles'   => [Admin::ROLE],
						'allow'   => false,
					],
					[
						'roles' => ['@'],
						'allow' => true,
					],
				],
			],
		];
	}

	public function actions() {
		return [
//			'error'   => [
//				'class' => 'yii\web\ErrorAction',
//			],
			'captcha' => [
				'class'           => 'yii\captcha\CaptchaAction',
				'fixedVerifyCode' => YII_ENV_TEST? 'testme': null,
			],
		];
	}

	public function actionIndex() {
		$newVideos = Video::find()->all();
		$categories = VideoCategory::find()->all();
		return $this->render('index', [
			'newVideos'  => $newVideos,
			'categories' => $categories,
		]);
	}

	public function actionSearchByCategories() {
		$q = Yii::$app->request->getQueryParam('q', []);

		if (array_key_exists('categories', $q)) {
			$categoryIds = $q['categories'];
		} else {
			$categoryIds = [];
		}
		$videos = Video::find()->where(['categoryId' => $categoryIds])->all();
		return $this->render('search-by-categories-results', [
			'videos' => $videos,
		]);
	}

	public function actionVideoDetail($id) {
		$video = Video::find()->where('id = :id', [':id' => $id])->with('parts', 'uploader', 'documents')->one();
		return $this->render('video-detail', [
			'video' => $video,
		]);
	}

	public function actionLogin() {
		if (!\Yii::$app->user->isGuest) {
			return $this->goHome();
		}

		$model = new LoginForm();
		if ($model->load(Yii::$app->request->post()) && $model->login()) {
			return $this->goBack();
		} else {
			return $this->render('login', [
				'model' => $model,
			]);
		}
	}

	public function actionLogout() {
		Yii::$app->user->logout();

		return $this->goHome();
	}

	public function actionRegistration() {
		if (!\Yii::$app->user->isGuest) {
			return $this->goHome();
		}
		$this->view->title = Yii::t('common', 'Registration');

		$model = new RegistrationForm();

		if (Yii::$app->request->isPost) {
			$model->load(Yii::$app->request->post());
			if ($model->validate()) {
				$user = $model->createUser();
				$success = $user->save();
				Yii::$app->session->setFlash('registration', $success);
				if ($success) {
					return $this->redirect(['login']);
				} else {
					$model->addErrors($user->errors);
				}
			}
		}

		return $this->render('registration', [
			'model' => $model,
		]);
	}

	public function actionEditProfile() {
		$this->view->title = Yii::t('common', 'Edit profile');

		/** @var User $user */
		$user = Yii::$app->user->getIdentity();

		if (Yii::$app->request->isPost) {
			$success = false;
			$post = Yii::$app->request->post();
			if ($user->load($post)) {
				$success = $user->save();
			}

			// -- Save card
			$card = $user->card;
			\Stripe\Stripe::setApiKey(Yii::$app->params['stripeSecretKey']);
			// Create a Customer
			$customer = \Stripe\Customer::create([
				'source'      => $card->stripeToken,
				'description' => $user->email,
			]);
			$card->customerId = $customer->id;
			$success          = $card->save(false, ['customerId']);
			$user->userCardId = $card->id;
			$success          = $success && $user->update() !== false;
			// -- -- -- --

			Yii::$app->session->setFlash('registration', $success);
		}

		return $this->render('registration', [
			'model' => $user,
		]);
	}

	public function actionMyPage() {
		$categories = VideoCategory::find()->all();

		return $this->render('my-page', [
			'categories' => $categories,
		]);
	}

	public function actionDownloadDocument($id) {
		$document = VideoDocument::findOne($id);
		if (!$document) {
			throw new HttpException(404, Yii::t('common', 'Not Found'));
		}

		header('Content-Type: application/octet-stream');
		header("Content-Transfer-Encoding: Binary");
		header("Content-disposition: attachment; filename=\"" . $document->title . "\"");
		readfile(Yii::getAlias('@webroot') . $document->source);
	}
}

protected/views/layouts/admin.php
<?php
use yii\helpers\Html;

use yii\bootstrap\Nav;
//use yii\bootstrap\NavBar;
use app\assets\AdminAsset;
use yii\helpers\Url;

/* @var $this \yii\web\View */
/* @var $content string */

AdminAsset::register($this);

$action = Yii::$app->controller->action->id;
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
	<meta charset="<?= Yii::$app->charset ?>">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<?= Html::csrfMetaTags() ?>
	<title><?= Html::encode($this->title) ?></title>
	<?php $this->head() ?>
</head>
<body>
<?php if (!Yii::$app->user->isGuest) { ?>
<div class="container" style="padding-top: 15px">
	<?php
	$actionId = Yii::$app->controller->action->id;
	echo Nav::widget([
		'options' => ['class' => 'nav-tabs'],
		'items'   => [
			[
				'label' => Yii::t('common', 'Site'),
				'url'   => ['main/index'],
			],
			[
				'label'  => Yii::t('common', 'Viewer list'),
				'url'    => ['admin/viewer-list'],
				'active' => strpos($actionId, 'viewer') === 0,
			],
			[
				'label'  => Yii::t('common', 'Uploader list'),
				'url'    => ['admin/uploader-list'],
				'active' => strpos($actionId, 'uploader') === 0 || in_array($actionId, ['video-add', 'video-edit']),
			],
			[
				'label'  => Yii::t('common', 'Video category list'),
				'url'    => ['admin/video-category-list'],
				'active' => strpos($actionId, 'video-category') === 0,
			],
		],
	]); ?>
</div>
<?php } ?>

<?php $this->beginBody() ?>
<div class="content" style="padding-top: 40px;">
	<div class="container">
		<?= $content ?>
	</div>
</div>
<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

protected/views/layouts/main.php
<?php
use yii\helpers\Html;

use yii\bootstrap\Nav;
//use yii\bootstrap\NavBar;
use app\assets\AppAsset;
use yii\helpers\Url;

/* @var $this \yii\web\View */
/* @var $content string */

AppAsset::register($this);

$action = Yii::$app->controller->action->id;
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
	<meta charset="<?= Yii::$app->charset ?>">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<?= Html::csrfMetaTags() ?>
	<title><?= Html::encode($this->title) ?></title>
	<?php $this->head() ?>

</head>
<body>
<?php $this->beginBody() ?>

<?php if (!Yii::$app->user->isGuest) { ?>
	<div class="top-menu">
		<div class="container">
		</div>
	</div>
<?php } ?>
<header>
	<div class="container">
		<div class="row">
			<div class="col-sm-4">
				<a href="/" class="logo"></a>
			</div>
			<div class="col-sm-8">
				<div class="row white-bg">
					<?php if (Yii::$app->user->isGuest) { ?>
						<!--<div class="col-sm-3">
							<div class="search-form">
								<form action="">
									<input type="text" name="" id="" class="form-control form-control_search"
										   placeholder="動画を検索する">
								</form>
							</div>
						</div>-->
						<div class="col-sm-12">
							<form action="<?= Url::to(['main/login']) ?>" class="login-form__form" method="post">
								<div class="row">
									<div class="col-sm-4">
										<input class="form-control form-control_login-form" type="text"
										       name="LoginForm[username]" placeholder="ID">
									</div>
									<div class="col-sm-4">
										<input class="form-control form-control_login-form form-control_password"
										       type="password" name="LoginForm[password]" placeholder="パスワード">
									</div>
									<div class="col-sm-4">
										<button type="submit"
										        class="btn login-form__button"><?= Yii::t('common', 'Login') ?></button>
									</div>
								</div>
							</form>
						</div>
					<?php } else { ?>
						<?php
						/** @var \app\models\User|\app\models\Admin $user */
						$user = Yii::$app->user->getIdentity();
						$isAdmin = $user->role == \app\models\Admin::ROLE;
						$colNumber = $isAdmin? 4: 6;
						?>
						<div class="col-sm-<?= $colNumber ?>">
							<div class="login-form__login">
								<?= $user->getLogin(); ?>
							</div>
						</div>
						<div class="col-sm-<?= $colNumber ?>">
							<a href="<?= Url::to(['main/logout']) ?>"
							   class="btn login-form__button"><?= Yii::t('common', 'Logout') ?></a>
						</div>
						<?php if ($isAdmin) { ?>
							<div class="col-sm-4">
								<?= Html::a(Yii::t('common', 'Admin'), ['admin/index'], ['class' => 'btn login-form__button']); ?>
							</div>
						<?php } ?>
					<?php } ?>
				</div>

				<?php if (Yii::$app->user->isGuest) { ?>
					<div class="login-form row">
						<div class="login-form__blue">
							<a href="<?= Url::to(['main/registration']) ?>">新規会員登録</a>
						</div>
					</div>
				<?php } ?>
			</div>
		</div>
	</div>

	<nav class="header-nav">
		<div class="container">
			<a href="/" class="active">TOP</a>
			<a href="<?= Url::to(['main/new-video']) ?>">新着動画</a>
			<a href="<?= Url::to(['main/new-data']) ?>">新着資料</a>
			<a href="/blog/">ブログ</a>
			<a href="<?= Url::to(['main/seminar']) ?>">セミナー</a>
			<a href="<?= Url::to(['main/my-page']) ?>">マイページ</a>
		</div>
	</nav>
</header>
<div class="content">
	<div class="container">
		<?= $content ?>
	</div>
</div>
<footer>
	<div class="container">
		<div class="row">
			<div class="col-sm-4">
				<a href="/" class="logo"></a>
			</div>
			<div class="col-sm-8">
				<nav class="footer-nav">
					<a href="#">ヘルプ</a>
					<a href="#">利用規約</a>
					<a href="#">運営会社</a>
					<a href="#">お問い合わせ</a>
				</nav>
			</div>
		</div>
		<div class="copyright">
			Copyright 2016 Movie Site.Inc
		</div>
	</div>
</footer>
<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>