protected/controllers/AjaxController.php
<?php

namespace app\controllers;

use app\components\UserIdentity;
use app\models\Admin;
use app\models\Uploader;
use app\models\User;
use app\models\UserRate;
use app\models\UserVideoViewed;
use Yii;
use yii\filters\AccessControl;
use yii\web\HttpException;

class AjaxController extends BaseController {

	public $layout = false;

	public function behaviors() {
		return [
			'access' => [
				'class' => AccessControl::className(),
				'rules' => [
					[
						'actions' => ['download-document'],
						'roles'   => [Admin::ROLE],
						'allow'   => true,
					],
					[
						'roles' => [Admin::ROLE],
						'allow' => false,
					],
					[
						'roles' => [User::ROLE],
						'allow' => true,
					],
				],
			],
		];
	}

	public function actionSendFeedback() {
		$uploaderId = Yii::$app->request->post('uploaderId');
		$text       = Yii::$app->request->post('text');

		if (!$uploaderId || !$text) {
			throw new HttpException(400);
		}

		$uploader = Uploader::findOne($uploaderId);

		if (!$uploader) {
			throw new HttpException(404);
		}

		$sent = Yii::$app->mailer
			->compose()
			->setTextBody($text)
			->setFrom(Yii::$app->params['emailFrom'])
			->setTo($uploader->mail)
			->setSubject('Send from sakanet')
			->send();

		return (int) $sent;
	}

	public function actionRate($videoId, $value) {
		/** @var UserIdentity $user */
		$user   = Yii::$app->user;
		$userId = $user->getCleanId();

		$rate = UserRate::find()->where([
			'userId'  => $userId,
			'videoId' => $videoId,
		])->one();

		if (!$rate) {
			$rate          = new UserRate();
			$rate->userId  = $userId;
			$rate->videoId = $videoId;
		}
		$rate->rate = $value;
		return (int) $rate->save();
	}

	public function actionSetVideoViewed($videoId) {
		$userId = Yii::$app->user->getCleanId();
		if (UserVideoViewed::findOne([
			'userId'  => $userId,
			'videoId' => $videoId,
		])
		) {
			return 0;
		}
		$videoViewed             = new UserVideoViewed();
		$videoViewed->attributes = [
			'userId'  => $userId,
			'videoId' => $videoId,
		];
		return (int) $videoViewed->save();
	}

	public function actionPayWithCard($amount) {
		/** @var User $user */
		$user = Yii::$app->user->getIdentity();
		if (!$user->userCardId) {
			throw new HttpException(404, Yii::t('common', 'Card not found'));
		}

		$result = $user->card->pay($amount);
		return $result === true? 1: $result;
	}
}

protected/controllers/MainController.php
<?php

namespace app\controllers;

use app\models\User;
use app\models\Admin;
use app\models\RegistrationForm;
use app\models\Video;
use app\models\VideoCategory;
use Yii;
use yii\filters\AccessControl;
use app\models\LoginForm;
use yii\web\HttpException;
use app\models\VideoDocument;

class MainController extends BaseController {

	public function behaviors() {
		return [
			'access' => [
				'class' => AccessControl::className(),
				'rules' => [
					[
						'actions' => ['login', 'logout', 'index', 'search-by-categories', 'registration', 'error'],
						'allow'   => true,
					],
					[
						'actions' => ['edit-profile'],
						'roles'   => [Admin::ROLE],
						'allow'   => false,
					],
					[
						'roles' => ['@'],
						'allow' => true,
					],
				],
			],
		];
	}

	public function actions() {
		return [
//			'error'   => [
//				'class' => 'yii\web\ErrorAction',
//			],
			'captcha' => [
				'class'           => 'yii\captcha\CaptchaAction',
				'fixedVerifyCode' => YII_ENV_TEST? 'testme': null,
			],
		];
	}

	public function actionIndex() {
		$newVideos = Video::find()->all();
		$categories = VideoCategory::find()->all();
		return $this->render('index', [
			'newVideos'  => $newVideos,
			'categories' => $categories,
		]);
	}

	public function actionSearchByCategories() {
		$q = Yii::$app->request->getQueryParam('q', []);

		if (array_key_exists('categories', $q)) {
			$categoryIds = $q['categories'];
		} else {
			$categoryIds = [];
		}
		$videos = Video::find()->where(['categoryId' => $categoryIds])->all();
		return $this->render('search-by-categories-results', [
			'videos' => $videos,
		]);
	}

	public function actionVideoDetail($id) {
		$video = Video::find()->where('id = :id', [':id' => $id])->with('parts', 'uploader', 'documents')->one();
		return $this->render('video-detail', [
			'video' => $video,
		]);
	}

	public function actionLogin() {
		if (!\Yii::$app->user->isGuest) {
			return $this->goHome();
		}

		$model = new LoginForm();
		if ($model->load(Yii::$app->request->post()) && $model->login()) {
			return $this->goBack();
		} else {
			return $this->render('login', [
				'model' => $model,
			]);
		}
	}

	public function actionLogout() {
		Yii::$app->user->logout();

		return $this->goHome();
	}

	public function actionRegistration() {
		if (!\Yii::$app->user->isGuest) {
			return $this->goHome();
		}
		$this->view->title = Yii::t('common', 'Registration');

		$model = new RegistrationForm();

		if (Yii::$app->request->isPost) {
			$model->load(Yii::$app->request->post());
			if ($model->validate()) {
				$user = $model->createUser();
				$success = $user->save();
				Yii::$app->session->setFlash('registration', $success);
				if ($success) {
					return $this->redirect(['login']);
				} else {
					$model->addErrors($user->errors);
				}
			}
		}

		return $this->render('registration', [
			'model' => $model,
		]);
	}

	public function actionEditProfile() {
		$this->view->title = Yii::t('common', 'Edit profile');

		/** @var User $user */
		$user = Yii::$app->user->getIdentity();

		if (Yii::$app->request->isPost) {
			$success = false;
			$post = Yii::$app->request->post();
			if ($user->load($post)) {
				$success = $user->save();
			}

			// -- Save card
			$card = $user->card;
			\Stripe\Stripe::setApiKey(Yii::$app->params['stripeSecretKey']);
			// Create a Customer
			$customer = \Stripe\Customer::create([
				'source'      => $card->stripeToken,
				'description' => $user->email,
			]);
			$card->customerId = $customer->id;
			$success          = $card->save(false, ['customerId']);
			$user->userCardId = $card->id;
			$success          = $success && $user->update() !== false;
			// -- -- -- --

			Yii::$app->session->setFlash('registration', $success);
		}

		return $this->render('registration', [
			'model' => $user,
		]);
	}

	public function actionMyPage() {
		$categories = VideoCategory::find()->all();

		return $this->render('my-page', [
			'categories' => $categories,
		]);
	}

	public function actionDownloadDocument($id) {
		$document = VideoDocument::findOne($id);
		if (!$document) {
			throw new HttpException(404, Yii::t('common', 'Not Found'));
		}

		header('Content-Type: application/octet-stream');
		header("Content-Transfer-Encoding: Binary");
		header("Content-disposition: attachment; filename=\"" . $document->title . "\"");
		readfile(Yii::getAlias('@webroot') . $document->source);
	}
}

protected/views/main/contact.php
<?php
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\ContactForm */

$this->title = 'Contact';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-contact">
    <h1><?= Html::encode($this->title) ?></h1>

    <?php if (Yii::$app->session->hasFlash('contactFormSubmitted')): ?>

    <div class="alert alert-success">
        Thank you for contacting us. We will respond to you as soon as possible.
    </div>

    <p>
        Note that if you turn on the Yii debugger, you should be able
        to view the mail message on the mail panel of the debugger.
        <?php if (Yii::$app->mailer->useFileTransport): ?>
        Because the application is in development mode, the email is not sent but saved as
        a file under <code><?= Yii::getAlias(Yii::$app->mailer->fileTransportPath) ?></code>.
        Please configure the <code>useFileTransport</code> property of the <code>mail</code>
        application component to be false to enable email sending.
        <?php endif; ?>
    </p>

    <?php else: ?>

    <p>
        If you have business inquiries or other questions, please fill out the following form to contact us. Thank you.
    </p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>
                <?= $form->field($model, 'name') ?>
                <?= $form->field($model, 'email') ?>
                <?= $form->field($model, 'subject') ?>
                <?= $form->field($model, 'body')->textArea(['rows' => 6]) ?>
                <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                    'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                ]) ?>
                <div class="form-group">
                    <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                </div>
            <?php ActiveForm::end(); ?>
        </div>
    </div>

    <?php endif; ?>
</div>

protected/views/main/error.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $error \Exception */

$this->title = 'Error ' . @$error->statusCode;
?>
<div class="site-error">

	<h1><?= Html::encode($this->title) ?></h1>

	<?php if ($error) { ?>
		<div class="alert alert-danger">
			<?= nl2br(Html::encode($error->getMessage())) ?>
		</div>
	<?php } ?>

	<p>
		<?= Yii::t('common', 'The above error occurred while the Web server was processing your request.'); ?>
	</p>
	<p>
		<?= Yii::t('common', 'Please contact us if you think this is a server error. Thank you.'); ?>
	</p>
</div>

protected/views/main/index.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;

/**
 * @var yii\web\View                $this
 * @var \app\models\Video[]         $newVideos
 * @var \app\models\VideoCategory[] $categories
 */
$this->title = 'Homepage';
?>

<div class="row">
	<div class="col-sm-4">
		<div class="border-blue">
			<form action="<?= Url::to(['main/search-by-categories']) ?>">
				<div class="border-blue__header">
					<i class="icon-search"></i>
					<?= Yii::t('common', 'Search by categories') ?>
				</div>
				<div class="border-blue__body">
					<?php foreach ($categories as $category) { ?>
						<div class="checkbox">
							<label>
								<input type="checkbox" name="q[categories][]" value="<?= $category->id ?>">
								<?= $category->title ?>
							</label>
						</div>
					<?php } ?>
				</div>
				<button type="submit" class="border-blue__footer">
					<i class="icon-search icon-search_white"></i>
					<?= Yii::t('common', 'Search') ?>
				</button>
			</form>
		</div>

		<div class="border-green">
			<div class="border-green__body">
				<p><i class="icon-message"></i></p>
				<p>最新のマーケティング情報を
					メールで配信中</p>

				<input type="text" placeholder="Your email" class="form-control grey-input">
			</div>
			<div class="border-green__footer">
				無料登録する
			</div>
		</div>
	</div>
	<div class="col-sm-8">
		<h1 class="page-title"><?= Html::encode($this->title) ?></h1>
		<div class="row text-center">
			<?php
			$i = 0;
			foreach ($newVideos as $video) {
				if (!count($video->parts)) {
					continue;
				}
				if ($i % 2 == 0 && $i > 0) {
					echo '</div><div class="row text-center">';
				}
				$i++;
				?>
				<div class="col-sm-6">
					<?= $this->render('@parts/movie-item', [
						'video'             => $video,
						'asLink'            => true,
						'hideSpeedControls' => true,
						'hideDesc'          => true,
					]) ?>
				</div>
			<?php } ?>
		</div>
	</div>
</div>

protected/views/main/login.php
<?php
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */

$this->title = Yii::t('common', 'Login');
?>

<?= $this->render('@parts/simple-flash', ['flashId' => 'registration']) ?>

<div class="site-login">
	<h1 class="page-title"><?= Html::encode($this->title) ?></h1>

	<?php $form = ActiveForm::begin([
		'id'          => 'login-form',
		'fieldConfig' => [
			'template' => "<div class=\"row\"><div class=\"col-sm-4\">{label}</div>\n<div class=\"col-sm-8\">{input}{error}</div></div>",
		],
	]); ?>

	<?= $form->field($model, 'username') ?>

	<?= $form->field($model, 'password')->passwordInput() ?>

	<?= $form->field($model, 'rememberMe', [
//        'template' => "<div class=\"col-lg-offset-1 col-lg-3\">{input}</div>\n<div class=\"col-lg-8\">{error}</div>",
	])->checkbox() ?>

	<div class="form-group">
		<?= Html::submitButton(Yii::t('common', 'Login'), ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
	</div>

	<?php ActiveForm::end(); ?>
</div>

protected/views/main/my-page.php
<?php
use yii\helpers\Html;
use yii\helpers\Url;
use app\models\Video;

/**
 * @var                             $this yii\web\View
 * @var \app\models\VideoCategory[] $categories
 **/

$this->title = Yii::t('common', 'My page');
?>
<h1 class="page-title"><?= $this->title ?> <a class="btn btn-info pull-right" href="<?= Url::to(['main/edit-profile']) ?>"><?= Yii::t('common', 'Edit profile') ?></a></h1>

<p><?= Yii::t('common', 'Hello') . ' ' . Yii::$app->user->getIdentity()->getLogin() ?> さん</p>

<h3><?= Yii::t('common', 'Recommended videos') ?></h3>
<div class="row">
	<?php foreach (Video::getRecommendedVideos() as $video) { ?>
		<div class="col-sm-3 form-group">
			<?= $this->render('@parts/movie-item', [
				'video' => $video,
			]) ?>
		</div>
	<?php } ?>
</div>


<h3><?= Yii::t('common', 'Popular videos') ?></h3>
<div class="row">
	<?php foreach (Video::getPopularVideos() as $video) { ?>
		<div class="col-sm-3 form-group">
			<?= $this->render('@parts/movie-item', [
				'video' => $video,
			]) ?>
		</div>
	<?php } ?>
</div>

<div class="panel panel-default">
	<div class="panel-heading"><?= Yii::t('common', 'Search by categories') ?></div>

	<div class="panel-body">
		<form action="<?= Url::to(['main/search-by-categories']) ?>">
			<div class="row">
				<?php foreach ($categories as $category) { ?>
					<div class="col-sm-3 form-group">
						<div class="checkbox">
							<label>
								<input type="checkbox" name="q[categories][]" value="<?= $category->id ?>">
								<?= $category->title ?>
							</label>
						</div>
					</div>
				<?php } ?>
			</div>

			<div class="text-center">
				<?= Html::submitButton(Yii::t('common', 'Search'), ['class' => 'btn btn-primary']) ?>
			</div>
		</form>
	</div>
</div>

protected/views/main/search-by-categories-results.php
<?php
use yii\helpers\Html;
use yii\helpers\Url;
use app\models\Video;

/**
 * @var                             $this yii\web\View
 * @var \app\models\Video[]         $videos
 **/

$this->title = Yii::t('common', 'Search results');
?>

<?php if (count($videos) == 0) {
	echo '<div class="alert alert-warning">' . Yii::t('common', 'Empty list') . '</div>';
	return;
} ?>

<div class="row">
	<?php foreach ($videos as $video) { ?>
		<div class="col-sm-3 form-group">
			<?= $this->render('@parts/movie-item', [
				'video' => $video,
			]) ?>
		</div>
	<?php } ?>
</div>

protected/views/main/video-detail.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use \app\models\User;

/**
 * @var                     $this yii\web\View
 * @var \app\models\Video   $video
 * */
$this->title = Yii::t('common', 'Video detail');
?>

	<div class="row">
		<div class="col-sm-6">
			<div class="playlist js-playlist">
				<?php foreach ($video->parts as $i => $part) { ?>
					<div class="playlist__video" style="<?= $i == 0? 'display: block;': '' ?>" data-video-part="<?= $part->id ?>">
						<?= $this->render('@parts/video-frame', [
							'video' => $video,
							'part'  => $part,
						]) ?>
					</div>
				<?php } ?>

				<table class="table table-condensed table-hover playlist__table">
					<?php foreach ($video->parts as $i => $part) { ?>
						<tr class="<?= $i == 0? 'active': '' ?>">
							<td>
								<button class="btn btn-default" data-playlist-play data-play-part="<?= $part->id ?>" data-play-video-id="<?= $video->id ?>">
									<span class="glyphicon glyphicon-play"></span>
								</button>
							</td>
							<td>
								<span><?= $part->title ?></span>
							</td>
							<td>
								<span><span class="glyphicon glyphicon-time"></span>&nbsp;<?= $part->duration ?></span>
							</td>
						</tr>
					<?php } ?>
				</table>
				<?= $this->render('@parts/speed-controls', [
					'video' => $video,
				]); ?>
			</div>
		</div>
		<div class="col-sm-6">
			<h2><?= $video->title ?></h2>
			<p><?= $video->uploader->title ?></p>
			<div>
				<?= $video->description ?>
			</div>
			<p><?= Yii::t('common', 'Payment') ?>
				: <?= $video->payment? '¥' . Yii::$app->formatter->asDecimal($video->payment, 0): Yii::t('common', 'Free') ?>
				<?php if (Yii::$app->user->can(User::ACTIONS) && !$video->checkIsAvailable()) { ?>
					<button class="btn btn-success js-fancybox-open"
					        data-target="#pay-popup"><?= Yii::t('common', 'Pay') ?></button>
				<?php } ?>
			</p>
			<p><?= Yii::t('common', 'Total length') ?>: <?= $video->getTotalDuration() ?></p>
			<p><?= Yii::t('common', 'Total parts') ?>: <?= $video->getPartsCount() ?></p>
			<p>
				<?= Yii::t('common', 'Rating') ?>:
				<span class="js-rate-it" data-rateit-readonly="true" data-rateit-value="<?= $video->rating ?>"></span>
				<?php if (Yii::$app->user->can(User::ACTIONS)) { ?>
					<button class="btn btn-info js-fancybox-open"
					        data-target="#rate-popup"><?= Yii::t('common', 'Rate') ?></button>
				<?php } ?>
			</p>
		</div>
	</div>

	<div class="row">
		<div class="col-sm-8">
			<ul class="nav nav-tabs">
				<li class="active">
					<a class="dropdown-toggle" data-toggle="tab" href="#documents" role="button" aria-haspopup="true"
					   aria-expanded="false">
						<?= Yii::t('common', 'Documents') ?>
					</a>
				</li>
				<li>
					<a class="dropdown-toggle" data-toggle="tab" href="#feedback" role="button" aria-haspopup="true"
					   aria-expanded="false">
						<?= Yii::t('common', 'Feedback') ?>
					</a>
				</li>
			</ul>
			<div id="myTabContent" class="tab-content">
				<div role="tabpanel" class="tab-pane fade active in" id="documents">
					<?php foreach ($video->documents as $document) { ?>
						<p><a href="<?= Url::to(['download-document', 'id' => $document->id]) ?>" target="_blank"
						      class="btn btn-primary"><?= $document->getName() ?></a></p>
					<?php } ?>
				</div>
				<div role="tabpanel" class="tab-pane fade" id="feedback">
					<div class="form-group">
						<textarea id="send-feedback-text" rows="6" class="form-control"
						          data-uploader-id="<?= $video->uploaderId ?>"
						          data-url="<?= Url::to(['ajax/send-feedback']) ?>"
						          placeholder="<?= Yii::t('common', 'Review') ?>"></textarea>
					</div>
					<button class="btn btn-primary js-send-feedback"
					        data-target="#send-feedback-text"><?= Yii::t('common', 'Send') ?></button>
				</div>
			</div>
		</div>
		<div class="col-sm-4">
			<h3><?= Yii::t('common', 'Related videos') ?></h3>
			<?php foreach ($video->getRelatedVideos() as $relatedVideo) {
				echo $this->render('@parts/movie-item', [
					'video'             => $relatedVideo,
					'asLink'            => true,
					'hideSpeedControls' => true,
					'hideDesc'          => true,
				]);
			} ?>
		</div>
	</div>

<?php if (Yii::$app->user->can(User::ACTIONS)) { ?>
	<div style="display: none;" id="rate-popup">
		<div class="text-center">
			<h4 class="nobr"><?= Yii::t('common', 'Rate this video') ?></h4>
			<span class="js-rate-it" data-rateit-value="<?= @$video->userRate->rate ?>"
			      data-video-id="<?= $video->id ?>" data-url="<?= Url::to(['ajax/rate']) ?>"></span>
		</div>
	</div>

	<div style="display: none;" id="pay-popup" class="text-center">
		<h4><?= Yii::t('common', 'Pay with the card that has wound') ?></h4>
		<?php if (Yii::$app->user->getIdentity()->userCardId) { ?>
			<div class="form-group">
				<button class="btn btn-success js-card-pay"
				        data-url="<?= Url::to(['ajax/pay-with-card', 'amount' => $video->payment]) ?>"><?= Yii::t('common', 'Yes') ?></button>
				<button class="btn btn-danger" onclick="$.fancybox.close();"><?= Yii::t('common', 'No') ?></button>
			</div>
		<?php } else { ?>
			<h4><?= Yii::t('common', 'You have no registered card') ?></h4>
			<div><a class="btn btn-primary"
			        href="<?= Url::to(['main/edit-profile']) ?>"><?= Yii::t('common', 'Register a card') ?></a>
			</div>
		<?php } ?>
	</div>
<?php } ?>