protected/controllers/MainController.php
<?php

namespace app\controllers;

use app\models\User;
use app\models\Admin;
use app\models\RegistrationForm;
use app\models\Video;
use app\models\VideoCategory;
use Yii;
use yii\filters\AccessControl;
use app\models\LoginForm;
use yii\web\HttpException;
use app\models\VideoDocument;

class MainController extends BaseController {

	public function behaviors() {
		return [
			'access' => [
				'class' => AccessControl::className(),
				'rules' => [
					[
						'actions' => ['login', 'logout', 'index', 'search-by-categories', 'registration', 'error'],
						'allow'   => true,
					],
					[
						'actions' => ['edit-profile'],
						'roles'   => [Admin::ROLE],
						'allow'   => false,
					],
					[
						'roles' => ['@'],
						'allow' => true,
					],
				],
			],
		];
	}

	public function actions() {
		return [
//			'error'   => [
//				'class' => 'yii\web\ErrorAction',
//			],
			'captcha' => [
				'class'           => 'yii\captcha\CaptchaAction',
				'fixedVerifyCode' => YII_ENV_TEST? 'testme': null,
			],
		];
	}

	public function actionIndex() {
		$newVideos = Video::find()->all();
		$categories = VideoCategory::find()->all();
		return $this->render('index', [
			'newVideos'  => $newVideos,
			'categories' => $categories,
		]);
	}

	public function actionSearchByCategories() {
		$q = Yii::$app->request->getQueryParam('q', []);

		if (array_key_exists('categories', $q)) {
			$categoryIds = $q['categories'];
		} else {
			$categoryIds = [];
		}
		$videos = Video::find()->where(['categoryId' => $categoryIds])->all();
		return $this->render('search-by-categories-results', [
			'videos' => $videos,
		]);
	}

	public function actionVideoDetail($id) {
		$video = Video::find()->where('id = :id', [':id' => $id])->with('parts', 'uploader', 'documents')->one();
		return $this->render('video-detail', [
			'video' => $video,
		]);
	}

	public function actionLogin() {
		if (!\Yii::$app->user->isGuest) {
			return $this->goHome();
		}

		$model = new LoginForm();
		if ($model->load(Yii::$app->request->post()) && $model->login()) {
			return $this->goBack();
		} else {
			return $this->render('login', [
				'model' => $model,
			]);
		}
	}

	public function actionLogout() {
		Yii::$app->user->logout();

		return $this->goHome();
	}

	public function actionRegistration() {
		if (!\Yii::$app->user->isGuest) {
			return $this->goHome();
		}
		$this->view->title = Yii::t('common', 'Registration');

		$model = new RegistrationForm();

		if (Yii::$app->request->isPost) {
			$model->load(Yii::$app->request->post());
			if ($model->validate()) {
				$user = $model->createUser();
				$success = $user->save();
				Yii::$app->session->setFlash('registration', $success);
				if ($success) {
					return $this->redirect(['login']);
				} else {
					$model->addErrors($user->errors);
				}
			}
		}

		return $this->render('registration', [
			'model' => $model,
		]);
	}

	public function actionEditProfile() {
		$this->view->title = Yii::t('common', 'Edit profile');

		/** @var User $user */
		$user = Yii::$app->user->getIdentity();

		if (Yii::$app->request->isPost) {
			$success = false;
			$post = Yii::$app->request->post();
			if ($user->load($post)) {
				$success = $user->save();
			}

			// -- Save card
			$card = $user->card;
			\Stripe\Stripe::setApiKey(Yii::$app->params['stripeSecretKey']);
			// Create a Customer
			$customer = \Stripe\Customer::create([
				'source'      => $card->stripeToken,
				'description' => $user->email,
			]);
			$card->customerId = $customer->id;
			$success          = $card->save(false, ['customerId']);
			$user->userCardId = $card->id;
			$success          = $success && $user->update() !== false;
			// -- -- -- --

			Yii::$app->session->setFlash('registration', $success);
		}

		return $this->render('registration', [
			'model' => $user,
		]);
	}

	public function actionMyPage() {
		$categories = VideoCategory::find()->all();

		return $this->render('my-page', [
			'categories' => $categories,
		]);
	}

	public function actionDownloadDocument($id) {
		$document = VideoDocument::findOne($id);
		if (!$document) {
			throw new HttpException(404, Yii::t('common', 'Not Found'));
		}

		header('Content-Type: application/octet-stream');
		header("Content-Transfer-Encoding: Binary");
		header("Content-disposition: attachment; filename=\"" . $document->title . "\"");
		readfile(Yii::getAlias('@webroot') . $document->source);
	}
}

protected/views/_parts/card-form.php
<?php
use yii\helpers\Url;
use yii\bootstrap\ActiveForm;
use yii\helpers\Html;

/**
 * @var \app\models\User $model
 * @var yii\web\View     $this
 */
$card = $model->card;

$this->registerJsFile('https://js.stripe.com/v2/');
$stripeKey = Yii::$app->params['stripePublicKey'];
$js = <<< JS
	$(function() {
		Stripe.setPublishableKey('{$stripeKey}');
		var form$ = $('#card-form').on('submit', function () {
			$.fancybox.showLoading();
			Stripe.card.createToken({
				number: $('#usercard-number').val(),
				cvc: $('.card-cvc').val(),
				exp_month: $('#usercard-month').val(),
				exp_year: $('#usercard-year').val(),
				name: $('#usercard-cvv').val()
			}, function (status, response) {
				$.fancybox.hideLoading();
				if (response.error) {
					$('#card-form-alert')
						.text(response.error.message)
						.show();
				} else {
					// token contains id, last4, and card type
					var token = response['id'];
					// insert the token into the form so it gets submitted to the server
					$('#usercard-stripetoken').val(token);
					// and submit
					form$.get(0).submit();
				}
			});
			return false;
		});
	});
JS;
$this->registerJs($js);
?>

<h2 class="text-center post-y-1"><?= Yii::t('common', 'Payment info') ?></h2>

<?php if ($model->userCardId) { ?>
	<p>Card saved. Customer ID <?= $model->card->customerId ?>.</p>
	<?php return; ?>
<?php } ?>

<div id="card-form-alert" class="alert alert-danger" style="display: none"><?= Yii::t('common', 'Error') ?></div>
<div>
	<?php $form = ActiveForm::begin([
		'id'          => 'card-form',
		'options'     => ['class' => 'form-vertical'],
		'fieldConfig' => [
			'template' => "<div class=\"row\"><div class=\"col-sm-4\">{label}</div>\n<div class=\"col-sm-4\">{input}{error}</div></div>",
		],
	]); ?>

	<?= $form->field($card, 'stripeToken', ['template' => '{input}'])->hiddenInput() ?>

	<?php /*$form->field($card, 'type', [
		'template' => '<div class="form-group">{input}{error}</div>',
	])->radioList($card::getTypes(), [
		'unselect'    => 0,
		'itemOptions' => [
			'labelOptions' => ['class' => 'radio-inline'],
		],
	])*/ ?>
	<?= $form->field($card, 'holderName') ?>
	<?= $form->field($card, 'number') ?>
	<?php $years = $card::getValidYears(); ?>
	<?= $form->field($card, 'year')->dropDownList(array_combine($years, $years)) ?>
	<?php $months = $card::getValidMonth(); ?>
	<?= $form->field($card, 'month')->dropDownList(array_combine($months, $months)) ?>
	<?= $form->field($card, 'cvv')->passwordInput() ?>

	<div class="form-group text-center">
		<?= Html::submitButton(Yii::t('common', 'Save'), ['class' => 'btn btn-primary', 'name' => 'registration-button']) ?>
	</div>

	<?php ActiveForm::end(); ?>
</div>

protected/views/_parts/movie-item.php
<?php
use yii\helpers\Url;

/**
 * @var \app\models\Video $video
 * @var bool              $showAll           Whether to show all the parts of video
 * @var bool              $asLink            Whether to go to the video detail by click
 * @var bool              $hideSpeedControls Whether to show speed control buttons
 * @var bool              $hideDesc          Whether to show description below video. Hidden on homepage
 */

$showAll           = isset($showAll)? $showAll: false;
$asLink            = isset($asLink)? $asLink: false;
$hideSpeedControls = isset($hideSpeedControls)? $hideSpeedControls: false;
$hideDesc          = isset($hideDesc)? $hideDesc: false;
?>
	<div
		class="movie-item" <?= $asLink? 'onclick="location.href = \'' . Url::to(['main/video-detail', 'id' => $video->id]) . '\';"': '' ?>>
		<?php if (count($video->parts)) {
			if ($showAll) {
				foreach ($video->parts as $part) {
					echo $this->render('@parts/video-frame', [
						'video'        => $video,
						'part'         => $part,
						'hideControls' => $asLink,
					]);
				}
			} else {
				echo $this->render('@parts/video-frame', [
					'video'        => $video,
					'part'         => $video->parts[0],
					'hideControls' => $asLink,
				]);
			}
		}
		?>
		<div class="movie-item__title"><?= $video->title ?></div>
		<?php if (!$hideDesc) { ?>
			<div class="movie-item__desc"><?= $video->description ?></div>
		<?php } ?>
	</div>
<?php if (!$hideSpeedControls) {
	echo $this->render('@parts/speed-controls', [
		'video' => $video,
	]);
} ?>

protected/views/_parts/simple-flash.php
<?php
/**
 * @var string $flashId
 */
$flash = Yii::$app->session->getFlash($flashId);
if ($flash !== null) {
	if ($flash) { ?>
		<div class="alert alert-success"><?= Yii::t('common', 'Successful') ?></div>
	<?php } else { ?>
		<div class="alert alert-danger"><?= Yii::t('common', 'Error') ?></div>
	<?php }
}

protected/views/_parts/speed-controls.php
<?php
/**
 * @var \app\models\Video $video
 */
?>
<div class="form-group">
	<button class="btn btn-primary js-video-speed" data-rate="1" data-video-id="<?= $video->id ?>">1X</button>
	<button class="btn btn-info js-video-speed" data-rate="1.5" data-video-id="<?= $video->id ?>">1.5X</button>
	<button class="btn btn-warning js-video-speed" data-rate="2" data-video-id="<?= $video->id ?>">2X</button>
</div>

protected/views/_parts/video-frame.php
<?php
/**
 * @var \app\models\Video     $video
 * @var \app\models\VideoPart $part
 */
$hideControls = isset($hideControls)? $hideControls: false;
?>
<?php if ($video->checkIsAvailable()) { ?>
<video <?= $hideControls? '': 'controls' ?> class="js-video video" data-id="<?= $video->id ?>" id="<?= $video->id ?>" poster="<?= $part->preview ?>">
	<source src="<?= $part->source ?>"
	        type="video/<?= pathinfo($part->source, PATHINFO_EXTENSION) ?>">
</video>
<?php } else { ?>
	<div class="panel panel-danger">
		<div class="panel-heading"><h3 class="panel-title"><?= Yii::t('common', 'Video unavailable') ?></h3></div>
		<div class="panel-body"><?= Yii::t('common', 'Sorry, you must pay for this video') ?></div>
	</div>
<?php } ?>